export const colorStyles = {
  emerald: {
    text: "text-emerald-600",
    border: "border-emerald-600",
    hoverBg: "hover:bg-emerald-50",
    icon: "text-emerald-600",
    mid: "bg-emerald-200",
    lightest: "bg-emerald-50",
    borderLight: "border-emerald-200",
    gradientFrom: "from-emerald-50",
    gradientTo: "to-white",
  },
  amber: {
    text: "text-amber-600",
    border: "border-amber-600",
    hoverBg: "hover:bg-amber-50",
    icon: "text-amber-600",
    mid: "bg-amber-200",
    lightest: "bg-amber-50",
    borderLight: "border-amber-200",
    gradientFrom: "from-amber-50",
    gradientTo: "to-white",
  },
  red: {
    text: "text-pink-600",
    border: "border-pink-600",
    hoverBg: "hover:bg-pink-50",
    icon: "text-pink-600",
    mid: "bg-pink-200",
    lightest: "bg-pink-50",
    borderLight: "border-pink-200",
    gradientFrom: "from-pink-50",
    gradientTo: "to-white",
  },
  sky: {
    text: "text-sky-600",
    border: "border-sky-600",
    hoverBg: "hover:bg-sky-50",
    icon: "text-sky-600",
    mid: "bg-sky-200",
    lightest: "bg-sky-50",
    borderLight: "border-sky-200",
    gradientFrom: "from-sky-50",
    gradientTo: "to-white",
  },
  purple: {
    text: "text-purple-600",
    border: "border-purple-600",
    hoverBg: "hover:bg-purple-50",
    icon: "text-purple-600",
    mid: "bg-purple-200",
    lightest: "bg-purple-50",
    borderLight: "border-purple-200",
    gradientFrom: "from-purple-50",
    gradientTo: "to-white",
  },
  slate: {
    text: "text-slate-500",
    border: "border-slate-500",
    hoverBg: "hover:bg-slate-100",
    icon: "text-slate-500",
    mid: "bg-slate-200",
    lightest: "bg-slate-50",
    borderLight: "border-slate-200",
    gradientFrom: "from-slate-50",
    gradientTo: "to-white",
  },
}; 