export const colorStyles = {
  green: {
    text: "text-green-600",
    border: "border-green-600",
    hoverBg: "hover:bg-green-50",
    icon: "text-green-600",
    mid: "#86efac",
    lightest: "#dcfce7",
    borderLight: "#bbf7d0",
  },
  orange: {
    text: "text-orange-600",
    border: "border-orange-600",
    hoverBg: "hover:bg-orange-50",
    icon: "text-orange-600",
    mid: "#fdba74",
    lightest: "#ffedd5",
    borderLight: "#fed7aa",
  },
  red: {
    text: "text-pink-600",
    border: "border-pink-600",
    hoverBg: "hover:bg-pink-50",
    icon: "text-pink-600",
    mid: "#f9a8d4",
    lightest: "#ffe4e6",
    borderLight: "#fecdd3",
  },
  sky: {
    text: "text-sky-600",
    border: "border-sky-600",
    hoverBg: "hover:bg-sky-50",
    icon: "text-sky-600",
    mid: "#38bdf8",
    lightest: "#e0f2fe",
    borderLight: "#bae6fd",
  },
  purple: {
    text: "text-purple-600",
    border: "border-purple-600",
    hoverBg: "hover:bg-purple-50",
    icon: "text-purple-600",
    mid: "#a5b4fc",
    lightest: "#ede9fe",
    borderLight: "#ddd6fe",
  },
  slate: {
    text: "text-slate-400",
    border: "border-slate-300",
    bg: "bg-slate-100",
    icon: "text-slate-400",
    mid: "#cbd5e1",
    lightest: "#f1f5f9",
    borderLight: "#e2e8f0",
  },
};
